### ISSUE TITLE
req.hostname returns undefined when is running as docker stack in the staging server

### ISSUE THREAD

**Issue by brucegroverlee** [sherpon/virtualhost#1]
docker-compose.yml
```yaml
version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: sherpon/virtualhost:http
    # Set environment variables in containers
    environment:
      - DOTENV_PATH="/srv/virtualhost/env/staging.env"
    env_file: /home/brucegrover_lee/virtualhost_docker/env/staging.env
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "443:443"
      - "7000:7000"
    # Set volume
    volumes:
      - $PWD/virtualhost_docker:/srv/virtualhost
    networks:
      - webnet
networks:
  webnet:
```

docker cmd's
```sh
sudo docker swarm init
sudo docker stack deploy -c docker-compose.yml vh
```
virtualhostApp.js
```js
app.use( async (req, res, next) => {
  /**
   * TO-DO 
   * req.hostname returns undefined when is running as docker stack in the staging server
   */
  const domain = req.hostname;
  const result = allDomainRegex.test(domain);
  if (!result) {
    next();
  }
  console.log('DOMAIN');
  console.log(domain);

  console.log('PUBLIC_DIRECTORY DOMAIN');
  console.log(`${process.env.PUBLIC_DIRECTORY}/${domain}`);
```
returns
```sh
 > virtualhost@1.0.0 http /usr/src/app
 > node ./src/virtualhostApp.js
 
 DOTENV_PATH
 "/srv/virtualhost/env/staging.env"
 STATICS_DIRECTORY
 /srv/virtualhost/statics
 NODE_ENV: staging
 Sherpon Virtualhost running on http://*.localhost:80/
 DOMAIN
 undefined
 PUBLIC_DIRECTORY DOMAIN
 /srv/virtualhost/public/undefined
 ::ffff:10.255.0.2 - - [07/Jul/2019:20:02:02 +0000] "GET / HTTP/1.0" 404 42 "-" "-"
```
